# Generated by Django 5.0.3 on 2024-03-08 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_list_item_delete_listitem'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='list_item',
            new_name='ListItem',
        ),
    ]
