# Generated by Django 5.0.3 on 2024-03-08 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_rename_list_item_listitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listitem',
            name='completed',
        ),
        migrations.RemoveField(
            model_name='listitem',
            name='due_date',
        ),
    ]
