# Generated by Django 5.0.3 on 2024-03-28 20:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0007_listitem_user_alter_listitem_due_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listitem',
            name='user',
        ),
        migrations.AlterField(
            model_name='listitem',
            name='due_date',
            field=models.DateField(default=datetime.date(2024, 3, 28)),
        ),
    ]
